sudo: required
language: python
python:
- 3.6
install:
- pip install tox-travis
script:
- tox
deploy:
  provider: pypi
  user: smnmtzgr
  password:
    secure: GgW+a10ZfhqyMJDoWU2OaniTwmzErk4ucnALI2yDNYmisq0yDjXdv6SABqQVIz1ol4sr+nGl49hZWNzisFLqXaE5GTnFAm9AvjDotckjhYojsDo4RPmOmdqrWUJs8wlOkeS6bWLOFY7bbbML4Bu9x1HEDeudawnIw2S2Wg9CgtFVEFUZn+vcHZMb4OaaVDNCrzVxIftLZGVc5JdjlU/Odt5rFBbV0/sWvJDaIvCQ+o7Evxi4hI86TtDkY+VImhwyeUFZHpx4txCNf0Tr7TDLAwenOele/xZDOHmqlQZo3aw6IiK2SAhi1wyWnuXmIoFVseCXfWv984AkP68Zuf5ugaiAIpZvtICfQqtK0SBLwqzhK3e9T4uhkTApd2U0j7UmT6vKC5ri/19OYuixzNShmdieuZlo96oCN6rgshVa77b5AsZtxz3PU/LmECfelgsHZWUIaGbxLm5KzDy5VA6fP9uyaF6CswyFotQdXfV3AtJV7LAn9T/T+MB/JchT20AEXsQSloUj7PbSh3cKn4fe/nCJ98GtKnjQ+MqSd8NfTO47urOqwuzbq+LBzkJHWJztLKaV+kSnQVrKaWDfQnJGuiaZi4rGUTqWsCuv7ebcixkMt170nq+Fz3V5TUZrDGb3uhQflDAzcK1vYw7VxjvDqAtz7/3JPPG19FplXZPZ92A=
  on:
    tags: true
    repo: dm-drogeriemarkt/nesbi
