sudo: required
language: python
python:
- 3.6
install:
- pip install tox-travis
script:
- tox
deploy:
  provider: pypi
  user: smnmtzgr
  password:
    secure: qV2OStAwxBzGCY/bpTPlKzndwIVlmcn0WSuQAGvio+P6VmhK6Z31URGxM+cvXIKdJwkbTQtvuMT/eWB9MYQe6B2fX1yR+jqmZ288gEGJdKzhSdM00bAFNZ61PM5eJxFHKeh5EmQmhYPjTZT5PoA8UdQN7q2YIb7mcM8FcMTuQaKdjcVYTx1I/msQie6BAN/TAw262eabrFXyO5/zqKzI3GSmmu5ECPBrPg1ZOV5wZFoqHc/PA2fofppBYmSu1c3PyVHgzyKfl1R27y19MxUIqps5o62u5S9zNxiXCzy/7LzVxRUCtt2TKA50YA6yyUiDByEDnwrXFvniVBJv+xKu88wIjerjrsPvfoo1xOCfc8Tmog+rrBSGdT6wUH6rv3p4rWwgm7DELw68ufryJoSEg0mctSlXOG8hNKf98mT7dyvvpJ0tUQwIPH1ltFoP6yDcaPpmPm8M9RsIWRSJ0CqqtkSPoBw0PkfHpdsEb/Pt4NYRCp/6aBYlsIQTyr6AJBNcfqCTimoNmtTyD319tLTlr1wxkp8ZrFNjp00zA1YhMGymm4RE1UZGY/R7RlcPXbs0uvek3gpihvMfDkJQjB1cs0KHM75QjpRd5+Lrync7WdGZ168g9VQWoOeQixKige+IO5tk+GjEe21HzOt5QyzuaGvjepAqo5Bvg11QQPXjd0o=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: dm-drogeriemarkt/nesbi
    branch: master
